version: "3"

services:
  short-creator:
    build:
      context: .
      dockerfile: main.Dockerfile
#    env_file:
#      - .env
    environment:
      - DEV=false
      - LOG_LEVEL=trace
      - WHISPER_VERBOSE=true
      - DATA_DIR_PATH=data
#    ports:
#      - "3123:3123"
    entrypoint: ["node", "dist/index.js"]
